# Basic CI setup: Lint with ruff, run tests with pytest
name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ruff without running check or format
        uses: astral-sh/ruff-action@v3
        with:
          args: "--version"
      - name: Ruff lint
        run: ruff check --diff .
      - name: Ruff format
        run: ruff format --diff .
      # This isn't a general Python lint, this style is just used in this repository
      #- name: Prettier format
      #  run: npx prettier --prose-wrap always --check "**/*.md"

  #test:
  #  name: Run tests
  #  strategy:
  #    matrix:
  #      os: [ubuntu-latest, macos-latest, windows-latest]
  #  runs-on: ${{ matrix.os }}
  #  steps:
  #    - uses: actions/checkout@v4
  #    - uses: astral-sh/setup-uv@v3
  #    - run: uv run pytest
